const fs = require('fs');
let base = fs.readFileSync('quiz_funil_completo_v2.html', 'utf8');

// BR Version
let br = base.replace(/\.eq\('id', 1\)/g, '.eq(\'id\', 2)')
.replace(/As suas fotos estão a afastar clientes sem você perceber/g, 'Suas fotos estão afastando clientes sem você perceber')
.replace(/das artesãs perde vendas por causa de fotos/g, 'das artesãs perdem vendas por causa de fotos')
.replace(/Descubra em que situação está/g, 'Descubra em que situação você está')
.replace(/as minhas fotos não ficam como eu quero/g, 'minhas fotos não ficam como eu quero')
.replace(/Quero perceber o que posso melhorar no negócio/g, 'Quero entender o que posso melhorar no negócio')
.replace(/Escolha a que mais lhe toca/g, 'Escolha a que mais mexe com você')
.replace(/As fotos ficam feias/g, 'As fotos ficam feias')
.replace(/Esta artesã tirou esta foto na cozinha dela/g, 'Esta artesã tirou esta foto na cozinha dela')
.replace(/Com o telemóvel/g, 'Com o celular')
.replace(/Se pudesse fazer isto com todos os seus produtos — mudava as suas vendas/g, 'Se pudesse fazer isso com todos os seus produtos — mudaria suas vendas')
.replace(/É exatamente o que preciso/g, 'É exatamente o que eu preciso')
.replace(/funciona para mim/g, 'funciona pra mim')
.replace(/o que mais gostaria de ter/g, 'o que mais você gostaria de ter')
.replace(/Perceber se estou realmente a lucrar/g, 'Entender se estou realmente lucrando')
.replace(/O que mais a impede de dar o próximo passo/g, 'O que mais te impede de dar o próximo passo')
.replace(/Queremos perceber para mostrar/g, 'Queremos entender para mostrar')
.replace(/Tenho medo de não perceber de tecnologia/g, 'Tenho medo de não entender de tecnologia')
.replace(/Preocupa-me ter de dar acesso/g, 'Me preocupa ter que dar acesso')
.replace(/Se sabe usar o WhatsApp/g, 'Se você sabe usar o WhatsApp')
.replace(/A nossa IA corre nos nossos/g, 'A nossa IA roda nos nossos')
.replace(/Entra com/g, 'Você entra com')
.replace(/password/g, 'senha')
.replace(/app/g, 'aplicativo')
.replace(/Uma sessão de fotógrafo custa €80–120. O app custa €7,90 por mês e faz fotos ilimitadas. Paga-se na primeira foto./g, 'Uma sessão com fotógrafo custa caro. O aplicativo custa bem menos por mês e faz fotos ilimitadas. Se paga na primeira foto.')
.replace(/Em 5 minutos já está a tirar a primeira/g, 'Em 5 minutos você já está tirando a primeira')
.replace(/Não há curva de aprendizagem — há resultado/g, 'Não tem curva de aprendizado — o resultado é')
.replace(/Para lhe mostrar exemplos/g, 'Para te mostrar exemplos')
.replace(/o que mudava/g, 'o que mudaria')
.replace(/Cobrava mais e com mais confiança/g, 'Cobraria mais e com mais confiança')
.replace(/Publicava mais e atraía/g, 'Publicaria mais e atrairia')
.replace(/Trabalhava mais descansada/g, 'Trabalharia mais descansada')
.replace(/Finalmente via o negócio crescer/g, 'Finalmente veria o negócio crescer')
.replace(/O seu negócio está pronto/g, 'Seu negócio está pronto')
.replace(/resolve exatamente o que precisa/g, 'resolve exatamente o que você precisa');

fs.writeFileSync('quiz_br.html', br, 'utf8');

// ES Version
let es = base.replace(/\.eq\('id', 1\)/g, '.eq(\'id\', 3)')
.replace(/lang="pt"/g, 'lang="es"')
.replace(/Início/g, 'Inicio')
.replace(/Concluído!/g, '¡Completado!')
.replace(/Passo /g, 'Paso ')
.replace(/ de /g, ' de ')
.replace(/Voltar/g, 'Volver')
.replace(/As suas fotos estão a afastar clientes sem você perceber\?/g, '¿Tus fotos están alejando clientes sin que te des cuenta?')
.replace(/95% das artesãs perde vendas por causa de fotos — mesmo tendo produtos lindos. Descubra em que situação está./g, 'El 95% de las artesanas pierden ventas por culpa de las fotos, incluso teniendo productos hermosos. Descubre en qué situación estás.')
.replace(/Sim — as minhas fotos não ficam como eu quero/g, 'Sí — mis fotos no quedan como quiero')
.replace(/Às vezes consigo, às vezes não/g, 'A veces lo logro, a veces no')
.replace(/Quero perceber o que posso melhorar no negócio/g, 'Quiero entender qué puedo mejorar en mi negocio')
.replace(/Qual é a sua maior frustração agora\?/g, '¿Cuál es tu mayor frustración ahora?')
.replace(/Escolha a que mais lhe toca — sem julgamentos/g, 'Elige la que más te identifique — sin juzgar')
.replace(/Trabalho muito mas no fim do mês não sei se lucrei/g, 'Trabajo mucho pero a fin de mes no sé si tuve ganancias')
.replace(/As fotos ficam feias e o produto parece menos valioso/g, 'Las fotos quedan feas y el producto parece menos valioso')
.replace(/Dificuldade em cobrar o preço certo sem sentir culpa/g, 'Dificultad para cobrar el precio justo sin sentir culpa')
.replace(/Orçamentos e encomendas — é uma confusão constante/g, 'Presupuestos y pedidos — es una confusión constante')
.replace(/Esta artesã tirou esta foto na cozinha dela./g, 'Esta artesana tomó esta foto en su cocina.')
.replace(/Com o telemóvel. Sem preparação. Em 30 segundos — o Ateliê Criativo transformou assim:/g, 'Con el móvil. Sin preparación. En 30 segundos — el Atelier Creativo la transformó así:')
.replace(/Antes/g, 'Antes')
.replace(/Depois/g, 'Después')
.replace(/Se pudesse fazer isto com todos os seus produtos — mudava as suas vendas\?/g, 'Si pudieras hacer esto con todos tus productos, ¿cambiaría tus ventas?')
.replace(/Com certeza! É exatamente o que preciso/g, '¡Por supuesto! Es exactamente lo que necesito')
.replace(/Sim, parece incrível — quero ver mais/g, 'Sí, parece increíble — quiero ver más')
.replace(/Talvez — mas tenho dúvidas se funciona para mim/g, 'Tal vez — pero tengo dudas de si funciona para mí')
.replace(/Veja mais transformações — produtos como os seus/g, 'Mira más transformaciones — productos como los tuyos')
.replace(/Além das fotos — o que mais gostaria de ter no seu negócio\?/g, 'Además de las fotos — ¿qué más te gustaría tener en tu negocio?')
.replace(/Saber o preço certo de cada peça — sem adivinhar/g, 'Saber el precio correcto de cada pieza — sin adivinar')
.replace(/Orçamentos profissionais que fecham vendas/g, 'Presupuestos profesionales que cierran ventas')
.replace(/Gerir encomendas sem me perder/g, 'Gestionar pedidos sin perderme')
.replace(/Perceber se estou realmente a lucrar/g, 'Entender si realmente estoy ganando dinero')
.replace(/O que mais a impede de dar o próximo passo\?/g, '¿Qué es lo que más te impide dar el siguiente paso?')
.replace(/Queremos perceber para mostrar que já resolvemos isso/g, 'Queremos entenderlo para mostrarte que ya lo hemos resuelto')
.replace(/Tenho medo de não perceber de tecnologia/g, 'Tengo miedo de no entender la tecnología')
.replace(/Preocupa-me ter de dar acesso ao Google ou a contas/g, 'Me preocupa tener que dar acceso a Google o a mis cuentas')
.replace(/Não sei se vale o investimento para o meu negócio/g, 'No sé si vale la inversión para mi negocio')
.replace(/Não tenho tempo para aprender uma ferramenta nova/g, 'No tengo tiempo para aprender una herramienta nueva')
.replace(/Essas dúvidas são normais. E já estão resolvidas./g, 'Esas dudas son normales. Y ya están resueltas.')
.replace(/Se sabe usar o WhatsApp, sabe usar o Ateliê Criativo. Foi testado por senhoras de 55\+ anos — todas conseguiram sozinhas./g, 'Si sabes usar WhatsApp, sabes usar el Atelier Creativo. Fue probado por mujeres de más de 55 años y todas lo lograron solas.')
.replace(/Não precisa de nada. A nossa IA corre nos nossos servidores. Entra com e-mail e password — como qualquer app. Simples assim./g, 'No necesitas nada. Nuestra IA funciona en nuestros servidores. Entras con email y contraseña — como cualquier app. Así de simple.')
.replace(/Uma sessão de fotógrafo custa €80–120. O app custa €7,90 por mês e faz fotos ilimitadas. Paga-se na primeira foto./g, 'Una sesión de fotografía es costosa. La app cuesta mucho menos al mes y hace fotos ilimitadas. Se paga sola con la primera foto.')
.replace(/Em 5 minutos já está a tirar a primeira foto profissional. Não há curva de aprendizagem — há resultado imediato./g, 'En 5 minutos ya estás tomando tu primera foto profesional. No hay curva de aprendizaje — hay resultados inmediatos.')
.replace(/Faz sentido — quero ver a oferta/g, 'Tiene sentido — quiero ver la oferta')
.replace(/Tenho mais dúvidas mas quero continuar/g, 'Tengo más dudas pero quiero continuar')
.replace(/Que tipo de produto faz com as suas mãos\?/g, '¿Qué tipo de producto haces con tus manos?')
.replace(/Para lhe mostrar exemplos do seu nicho específico/g, 'Para mostrarte ejemplos de tu nicho específico')
.replace(/Outro produto feito à mão com amor/g, 'Otro producto hecho a mano con amor')
.replace(/Se tivesse tudo organizado amanhã — o que mudava\?/g, 'Si tuvieras todo organizado mañana — ¿qué cambiaría?')
.replace(/Cobrava mais e com mais confiança/g, 'Cobraría más y con más confianza')
.replace(/Publicava mais e atraía mais clientes/g, 'Publicaría más y atraería más clientes')
.replace(/Trabalhava mais descansada, sem confusão/g, 'Trabajaría más descansada, sin confusión')
.replace(/Finalmente via o negócio crescer de verdade/g, 'Finalmente vería crecer mi negocio de verdad')
.replace(/O seu diagnóstico está pronto/g, 'Tu diagnóstico está listo')
.replace(/O seu negócio está pronto para dar o salto./g, 'Tu negocio está listo para dar el salto.')
.replace(/Com base nas suas respostas — o Ateliê Criativo resolve exatamente o que precisa./g, 'Según tus respuestas — el Atelier Creativo resuelve exactamente lo que necesitas.')
.replace(/Fotos profissionais com IA — sem fotógrafo, sem estúdio/g, 'Fotos profesionales con IA — sin fotógrafo, sin estudio')
.replace(/Calculadora de preço justo — cobra com segurança/g, 'Calculadora de precio justo — cobra con seguridad')
.replace(/Orçamentos PDF com a sua marca — em 1 clique/g, 'Presupuestos PDF con tu marca — en 1 clic')
.replace(/Gestão de encomendas \+ financeiro completo/g, 'Gestión de pedidos + finanzas completas')
.replace(/Tudo num só app. Acesso imediato. Hoje./g, 'Todo en una sola app. Acceso inmediato. Hoy.')
.replace(/artesãs já usam/g, 'artesanas ya usan')
.replace(/gasto em fotógrafo/g, 'gastado en fotógrafo')
.replace(/garantia total/g, 'garantía total')
.replace(/Oferta especial por ter feito o quiz/g, 'Oferta especial por haber completado el quiz')
.replace(/Preço de lançamento disponível apenas hoje para quem chegou por aqui./g, 'Precio de lanzamiento disponible solo hoy para quienes llegaron por aquí.')
.replace(/Mensal/g, 'Mensual')
.replace(/Cancela quando quiser/g, 'Cancela cuando quieras')
.replace(/mês/g, 'mes')
.replace(/Mais Popular — Poupa/g, 'Más Popular — Ahorra')
.replace(/melhor oferta/g, 'mejor oferta')
.replace(/ano/g, 'año')
.replace(/Vitalício/g, 'Vitalicio')
.replace(/Paga uma vez · para sempre/g, 'Paga una vez · para siempre')
.replace(/única vez/g, 'única vez')
.replace(/Quero começar agora/g, 'Quiero empezar ahora')
.replace(/Garantia 7 dias/g, 'Garantía de 7 días')
.replace(/Acesso imediato/g, 'Acceso inmediato')
.replace(/Crochê, tricot, bordados, macramê, amigurumi/g, 'Ganchillo, tricot, bordados, macramé, amigurumi')
.replace(/Papelaria, sousplats, caixinhas, MDF, presentes/g, 'Papelería, bajoplatos, cajitas, MDF, regalos')
.replace(/Velas, sabonetes, aromas, cosméticos artesanais/g, 'Velas, jabones, aromas, cosméticos artesanales')
.replace(/Bijuteria, joias, acessórios personalizados/g, 'Bisutería, joyas, accesorios personalizados');

fs.writeFileSync('quiz_es.html', es, 'utf8');

console.log('Done!');
