const fs = require('fs');

let content = fs.readFileSync('es.html', 'utf-8');

const replacements = [
    [/lang="pt"/g, 'lang="es"'],
    [/Transforme suas fotos em vendas profissionais/g, 'Transforma tus fotos en ventas profesionales'],
    [/O Ateliê Criativo transforma fotos caseiras em imagens de catálogo profissional e organiza todo o seu negócio de artesanato\./g, 'El Atelier Creativo transforma fotos caseras en imágenes de catálogo profesional y organiza todo tu negocio de artesanía.'],
    [/⏳ Oferta termina em:/g, '⏳ Oferta termina en:'],
    [/Vitalício por €97/g, 'Vitalicio por $97'],
    [/apenas esta semana/g, 'solo esta semana'],
    [/Garantir Vaga/g, 'Asegurar mi lugar'],
    [/🧶 Artesanato · 📦 Papelaria · 🕯️ Velas · 🎀 Acessórios/g, '🧶 Artesanía · 📦 Papelería · 🕯️ Velas · 🎀 Accesorios'],
    [/já transformaram o negócio/g, 'ya transformaron su negocio'],
    [/Artesanato/g, 'Artesanía'],
    [/Papelaria/g, 'Papelería'],
    [/Velas/g, 'Velas'],
    [/Acessórios/g, 'Accesorios'],
    [/Antes/g, 'Antes'],
    [/✨ Depois/g, '✨ Después'],
    [/Fundo de trabalho bagunçado/g, 'Fondo de trabajo desordenado'],
    [/Luz profissional e pronta para vender/g, 'Luz profesional y lista para vender'],
    [/Fundo amador e sem contexto/g, 'Fondo amateur y sin contexto'],
    [/Cenário nórdico limpo e premium/g, 'Escenario nórdico limpio y premium'],
    [/Fundo de tapete e luz artificial/g, 'Fondo de alfombra y luz artificial'],
    [/Cenário zen e luz natural/g, 'Escenario zen y luz natural'],
    [/Fundo escuro e sombras/g, 'Fondo oscuro y sombras'],
    [/Cenário limpo e cores vivas/g, 'Escenario limpio y colores vivos'],
    [/Quero Garantir o Desconto/g, 'Quiero Asegurar el Descuento'],
    [/🎁 Bónus exclusivo para as próximas 24h/g, '🎁 Bono exclusivo por las próximas 24h'],
    [/Reconhece <em>alguma destas situações\?<\/em>/g, '¿Te identificas con <em>alguna de estas situaciones?</em>'],
    [/Se uma delas lhe soou familiar — este app foi feito para si/g, 'Si alguna te suena familiar — esta app fue hecha para ti'],
    [/Tira fotos dos seus produtos mas ficam sempre sem graça — e a cliente olha e não compra/g, 'Tomas fotos de tus productos pero siempre quedan sin gracia — el cliente mira y no compra'],
    [/A cliente pergunta o preço e você hesita, diz um número "de cabeça" — e no fim do mês o dinheiro some sem saber porquê/g, 'El cliente pregunta el precio y dudas, dices un número "de memoria" — y al final del mes el dinero desaparece sin saber por qué'],
    [/Envia o orçamento pelo WhatsApp, a cliente lê\.\.\. e não responde\. Ou pede desconto porque não parece profissional/g, 'Envías el presupuesto por WhatsApp, el cliente lee... y no responde. O pide descuento porque no parece profesional'],
    [/Encomendas anotadas num papel, num chat, numa folha — e às vezes perde-se, esquece ou confunde datas/g, 'Pedidos anotados en un papel, en un chat — y a veces se pierden, olvidas o confundes fechas'],
    [/Trabalha muito, a peça sai bonita — mas a sensação é que o negócio nunca cresce como devia/g, 'Trabajas mucho, la pieza sale hermosa — pero la sensación es que el negocio nunca crece como debería'],
    [/Não é falta de talento\. É falta de ferramenta certa\./g, 'No es falta de talento. Es falta de la herramienta correcta.'],
    [/E isso tem solução — rápida, simples e ao alcance de qualquer artesã\./g, 'Y eso tiene solución — rápida, simple y al alcance de cualquier artesana.'],
    [/Veja o app em <em>ação<\/em>/g, 'Mira la app en <em>acción</em>'],
    [/Resultados profissionais em menos de 1 minuto/g, 'Resultados profesionales en menos de 1 minuto'],
    [/100% feito com o Ateliê Criativo/g, '100% hecho con el Atelier Creativo'],
    [/Quero vender assim também/g, 'Quiero vender así también'],
    [/O seu estúdio completo,<br><em>na palma da mão<\/em>/g, 'Tu estudio completo,<br><em>en la palma de tu mano</em>'],
    [/A inteligência artificial que era só para grandes marcas — agora ao serviço da artesã/g, 'La inteligencia artificial que era solo para grandes marcas — ahora al servicio de la artesana'],
    [/Velas & Sabonetes/g, 'Velas & Jabones'],
    [/Diferencial único/g, 'Diferencial único'],
    [/Estúdio de Fotos com IA/g, 'Estudio de Fotos con IA'],
    [/Tire uma foto simples com o telemóvel\. A nossa IA troca o fundo, melhora a luz e entrega uma imagem digna de revista — em segundos\. <strong>Corre no nosso servidor\.<\/strong> Não precisa de autorizar o Google, nem de criar conta em lado nenhum\./g, 'Toma una foto simple con tu celular. Nuestra IA cambia el fondo, mejora la luz y entrega una imagen digna de revista — en segundos. <strong>Corre en nuestro servidor.</strong> No necesitas autorizar a Google, ni crear cuenta en ningún lado.'],
    [/Calculadora de Preço Justo/g, 'Calculadora de Precio Justo'],
    [/Materiais \+ horas \+ margem = preço com lucro real\. Nunca mais trabalhe de graça sem perceber\. Cobra com segurança e confiança\./g, 'Materiales + horas + margen = precio con ganancia real. Nunca más trabajes gratis sin darte cuenta. Cobra con seguridad y confianza.'],
    [/Orçamentos PDF em 1 clique/g, 'Presupuestos PDF en 1 clic'],
    [/Com a sua logo e as suas cores\. Enviado pelo WhatsApp em segundos\. A cliente recebe um documento profissional — e a confiança muda tudo\./g, 'Con tu logo y tus colores. Enviado por WhatsApp en segundos. El cliente recibe un documento profesional — y la confianza lo cambia todo.'],
    [/Contratos Personalizados/g, 'Contratos Personalizados'],
    [/Proteja o seu trabalho com contratos simples e profissionais\. Sem advogado\. Gerados pelo app com os dados da encomenda\./g, 'Protege tu trabajo con contratos simples y profesionales. Sin abogado. Generados por la app con los datos del pedido.'],
    [/Gestão de Encomendas/g, 'Gestión de Pedidos'],
    [/Todos os pedidos organizados, com prazo e estado\. Nunca mais se esqueça de uma entrega ou confunda uma cliente\./g, 'Todos los pedidos organizados, con plazo y estado. Nunca más olvides una entrega o confundas a un cliente.'],
    [/Financeiro Completo/g, 'Finanzas Completas'],
    [/Receitas, despesas e lucro real num só painel\. Feche o mês a saber exatamente quanto o seu ateliê gerou\./g, 'Ingresos, gastos y ganancia real en un solo panel. Cierra el mes sabiendo exactamente cuánto generó tu taller.'],
    [/Como funciona <em>em 3 passos<\/em>/g, 'Cómo funciona <em>en 3 pasos</em>'],
    [/Simples como deve ser\. Poderoso como o seu negócio merece\./g, 'Simple como debe ser. Poderoso como tu negocio merece.'],
    [/Tire a foto como sempre fez/g, 'Toma la foto como siempre lo hiciste'],
    [/Com o telemóvel, em qualquer sítio, com a luz que tiver\. Não precisa de equipamento especial nem de arrumar a casa toda\./g, 'Con el celular, en cualquier lugar, con la luz que tengas. No necesitas equipo especial ni ordenar toda la casa.'],
    [/Escolha o cenário — a IA trata do resto/g, 'Elige el escenario — la IA hace el resto'],
    [/Estúdio branco, mesa de madeira, fundo floral, jardim, rústico, minimalista — dezenas de cenários prontos\. Em segundos tem uma foto profissional com a sua peça em destaque\./g, 'Estudio blanco, mesa de madera, fondo floral, jardín, rústico, minimalista — decenas de escenarios listos. En segundos tienes una foto profesional.'],
    [/Publique, orce e venda mais/g, 'Publica, cotiza y vende más'],
    [/Fotos que param o scroll nas redes sociais\. Orçamentos PDF que fecham vendas\. Negócio organizado que finalmente cresce\./g, 'Fotos que detienen el scroll en redes sociales. Presupuestos PDF que cierran ventas. Negocio organizado que finalmente crece.'],
    [/Escolher meu plano e começar/g, 'Elegir mi plan y empezar'],
    [/Garantia incondicional de 15 dias/g, 'Garantía incondicional de 15 días'],
    [/O que dizem <em>as artesãs<\/em>/g, 'Lo que dicen <em>las artesanas</em>'],
    [/Histórias reais de quem já vive a transformação/g, 'Historias reales de quienes ya viven la transformación'],
    [/"Tirei uma foto do meu sousplat em cima da mesa da cozinha e ficou uma imagem de revista\. As clientes perguntam se contratei fotógrafo\. Respondo que sim — a inteligência artificial!"/g, '"Tomé una foto de mi sousplat en la mesa de la cocina y quedó una imagen de revista. Los clientes preguntan si contraté fotógrafo. Respondo que sí — ¡la inteligencia artificial!"'],
    [/Sousplats & cestaria · Braga/g, 'Sousplats & cestería · Madrid'],
    [/"Mandei o orçamento em PDF com a minha logo pela primeira vez\. A cliente respondeu de imediato: 'parece tão profissional, vou confirmar já\.' Nunca mais voltei ao WhatsApp simples\."/g, '"Envié el presupuesto en PDF con mi logo por primera vez. El cliente respondió de inmediato: \'parece tan profesional, voy a confirmar ya\'. Nunca más volví al WhatsApp simple."'],
    [/Papelaria personalizada · Lisboa/g, 'Papelería personalizada · Barcelona'],
    [/"Descobri que cobrava quase 30% abaixo do que devia\. A calculadora mostrou isso em 5 minutos\. Ajustei os preços — e as clientes nem pestanejaram\. Agora sei que estou a lucrar de verdade\."/g, '"Descubrí que cobraba casi 30% menos de lo que debía. La calculadora lo mostró en 5 minutos. Ajusté los precios y los clientes ni pestañearon. Ahora sé que estoy ganando de verdad."'],
    [/Velas artesanais · Porto/g, 'Velas artesanales · Valencia'],
    [/Quero os resultados dessas artesãs/g, 'Quiero los resultados de estas artesanas'],
    [/Acesso vitalício disponível por tempo limitado/g, 'Acceso vitalicio disponible por tiempo limitado'],
    [/Quanto custaria isto <em>separado\?<\/em>/g, '¿Cuánto costaría esto <em>por separado?</em>'],
    [/Veja o que está a poupar — tudo incluído num único app/g, 'Mira lo que estás ahorrando — todo incluido en una sola app'],
    [/Se fosse comprar cada peça separada, pagaria:/g, 'Si compraras cada pieza por separado, pagarías:'],
    [/Fotógrafo profissional/g, 'Fotógrafo profesional'],
    [/por sessão/g, 'por sesión'],
    [/Orçamento\/Contrato/g, 'Presupuesto/Contrato'],
    [/por template/g, 'por plantilla'],
    [/App de gestão/g, 'App de gestión'],
    [/só o básico/g, 'solo lo básico'],
    [/Calculadora de preços/g, 'Calculadora de precios'],
    [/serviço separado/g, 'servicio separado'],
    [/✦ Tudo junto aqui/g, '✦ Todo junto aquí'],
    [/por mês/g, 'por mes'],
    [/Tudo o que acima custaria/g, 'Todo lo anterior costaría'],
    [/está disponível por <strong>menos que um café por semana\.<\/strong>/g, 'está disponible por <strong>menos de un café a la semana.</strong>'],
    [/Com ou sem o Ateliê Criativo\. <em>Escolhe tu\.<\/em>/g, 'Con o sin el Atelier Creativo. <em>Tú eliges.</em>'],
    [/A diferença entre o negócio que sobrevive e o que cresce/g, 'La diferencia entre el negocio que sobrevive y el que crece'],
    [/Sem o app/g, 'Sin la app'],
    [/Com Ateliê Criativo/g, 'Con Atelier Creativo'],
    [/Fotos de produto/g, 'Fotos de producto'],
    [/Caseiras, sem cenário/g, 'Caseras, sin escenario'],
    [/Profissionais com IA/g, 'Profesionales con IA'],
    [/Preço das peças/g, 'Precio de las piezas'],
    [/No achismo, quase sempre a perder/g, 'Adivinando, casi siempre perdiendo'],
    [/Calculado com custo real/g, 'Calculado con costo real'],
    [/Orçamentos/g, 'Presupuestos'],
    [/Mensagem de WhatsApp/g, 'Mensaje de WhatsApp'],
    [/PDF com a sua marca/g, 'PDF con tu marca'],
    [/Contratos/g, 'Contratos'],
    [/Nenhum — trabalha a perder/g, 'Ninguno — trabajas perdiendo'],
    [/Gerados em 1 clique/g, 'Generados en 1 clic'],
    [/Pedidos de desconto/g, 'Pedidos de descuento'],
    [/Cede por não ter como justificar/g, 'Cedes por no poder justificar'],
    [/Mostra o cálculo — cliente entende/g, 'Muestras el cálculo — el cliente entiende'],
    [/Financeiro/g, 'Finanzas'],
    [/Sem saber se está a lucrar/g, 'Sin saber si estás ganando'],
    [/Lucro visível em cada pedido/g, 'Ganancia visible en cada pedido'],
    [/Imagem profissional/g, 'Imagen profesional'],
    [/Parece hobby/g, 'Parece un hobby'],
    [/Parece empresa de verdade/g, 'Parece una empresa de verdad'],
    [/Escolha o seu plano <em>hoje<\/em>/g, 'Elige tu plan <em>hoy</em>'],
    [/Menos que uma refeição fora — e transforma o seu ateliê por completo/g, 'Menos que una comida fuera — y transforma tu taller por completo'],
    [/Mensal/g, 'Mensual'],
    [/cancela quando quiser/g, 'cancela cuando quieras'],
    [/Fotos IA profissionais/g, 'Fotos IA profesionales'],
    [/Calculadora de preço/g, 'Calculadora de precio'],
    [/Assinar Mensal/g, 'Suscribirse Mensual'],
    [/⭐ Mais Popular/g, '⭐ Más Popular'],
    [/Anual/g, 'Anual'],
    [/equivale a/g, 'equivale a'],
    [/Poupa €60 por ano/g, 'Ahorras $60 al año'],
    [/Tudo do Mensal/g, 'Todo lo del Mensual'],
    [/Cenários premium/g, 'Escenarios premium'],
    [/Suporte prioritário/g, 'Soporte prioritario'],
    [/Todas as atualizações/g, 'Todas las actualizaciones'],
    [/Assinar Anual · Melhor Oferta/g, 'Suscribirse Anual · Mejor Oferta'],
    [/Vitalício ⚡/g, 'Vitalicio ⚡'],
    [/uma vez · acesso para sempre/g, 'una vez · acceso para siempre'],
    [/Apenas esta semana/g, 'Solo esta semana'],
    [/Tudo incluído para sempre/g, 'Todo incluido para siempre'],
    [/Todas as atualizações futuras/g, 'Todas las actualizaciones futuras'],
    [/Cenários ilimitados/g, 'Escenarios ilimitados'],
    [/Suporte vitalício/g, 'Soporte vitalicio'],
    [/Sem mensalidades nunca/g, 'Sin mensualidades nunca'],
    [/Acesso Vitalício/g, 'Acceso Vitalicio'],
    [/Cartão · MB Way · PayPal · Pix/g, 'Tarjeta · PayPal · Efectivo'],
    [/Pagamento seguro via Hotmart/g, 'Pago seguro vía Hotmart'],
    [/Acesso imediato/g, 'Acceso inmediato'],
    [/Garantia total de 15 dias — sem perguntas/g, 'Garantía total de 15 días — sin preguntas'],
    [/Experimente o Ateliê Criativo durante 15 dias completos\. Se por qualquer razão não ficar satisfeita — um e-mail e devolvemos tudo na hora\. Sem perguntas, sem formulários, sem esperas\. <strong>O risco é nosso\. O ganho é seu\.<\/strong>/g, 'Prueba el Atelier Creativo durante 15 días completos. Si por cualquier razón no quedas satisfecha — un correo y devolvemos todo al instante. Sin preguntas, sin formularios, sin esperas. <strong>El riesgo es nuestro. La ganancia es tuya.</strong>'],
    [/Perguntas <em>frequentes<\/em>/g, 'Preguntas <em>frecuentes</em>'],
    [/Tudo o que precisa saber antes de começar/g, 'Todo lo que necesitas saber antes de empezar'],
    [/Preciso de saber usar computador ou perceber de tecnologia\?/g, '¿Necesito saber usar computadora o entender de tecnología?'],
    [/Não\. Se sabe usar o WhatsApp, sabe usar o Ateliê Criativo\. Foi desenhado para ser simples e intuitivo, mesmo para quem nunca usou um app de negócio\./g, 'No. Si sabes usar WhatsApp, sabes usar el Atelier Creativo. Fue diseñado para ser simple e intuitivo.'],
    [/Tenho de autorizar o Google ou dar acesso à minha conta\?/g, '¿Tengo que autorizar a Google o dar acceso a mi cuenta?'],
    [/Não\. A nossa inteligência artificial corre nos nossos próprios servidores\. Não precisa de autorizar o Google, criar conta na OpenAI, nem dar acesso a absolutamente nada\. Entra no app, usa e pronto — simples assim\./g, 'No. Nuestra inteligencia artificial corre en nuestros propios servidores. No necesitas autorizar a Google ni crear cuentas externas.'],
    [/Quantas fotos posso fazer\?/g, '¿Cuántas fotos puedo hacer?'],
    [/Generosas para o uso normal de uma artesã ativa\. Muito acima do que os concorrentes oferecem \(alguns limitam a 4 fotos por dia mesmo cobrando mensalidade\)\. No plano vitalício o limite é consideravelmente maior\./g, 'Generosas para el uso normal de una artesana activa. Muy por encima de lo que ofrecen los competidores.'],
    [/Funciona para o tipo de artesanato que eu faço\?/g, '¿Funciona para el tipo de artesanía que hago?'],
    [/Sim — macramê, bordados, crochê, sousplats, velas, sabonetes, papelaria, bijuteria, joias, presentes personalizados, MDF, guirlandas, cestos, acessórios\. Se é feito com as mãos e com amor, o app foi feito para si\./g, 'Sí — macramé, bordados, crochet, velas, jabones, papelería, bisutería, MDF, accesorios. Si está hecho con las manos, la app fue hecha para ti.'],
    [/Estou em Portugal — o pagamento funciona\?/g, '¿Estoy en otro país — el pago funciona?'],
    [/Sim, perfeitamente\. Cartão de débito e crédito, MB Way e PayPal\. Valores em euros\. Fatura emitida automaticamente pela Hotmart\./g, 'Sí, perfectamente. Tarjeta de débito y crédito y PayPal. Valores en dólares. Pago procesado por Hotmart.'],
    [/Posso cancelar a qualquer momento\?/g, '¿Puedo cancelar en cualquier momento?'],
    [/No plano mensal, cancela quando quiser sem qualquer penalização\. No anual e vitalício tem sempre a garantia de 15 dias\. Sem letra pequena\./g, 'En el plan mensual, cancela cuando quieras sin penalización. En el anual y vitalicio tienes garantía de 15 días.'],
    [/O seu talento merece<br>uma vitrine <em>à sua altura\.<\/em>/g, 'Tu talento merece<br>una vitrina <em>a su altura.</em>'],
    [/Junte-se a centenas de artesãs que já pararam de trabalhar no escuro\.<br>Fotos profissionais\. Negócio organizado\. Lucro visível\. Hoje\./g, 'Únete a cientos de artesanas que ya dejaron de trabajar a oscuras.<br>Fotos profesionales. Negocio organizado. Ganancia visible. Hoy.'],
    [/Quero começar agora/g, 'Quiero empezar ahora'],
    
    // Currencies replacements
    [/€197/g, '$197'],
    [/€97/g, '$97'],
    [/€80–120/g, '$80–120'],
    [/€30–50/g, '$30–50'],
    [/€25\/mês/g, '$25/mes'],
    [/€15\/mês/g, '$15/mes'],
    [/€7,90/g, '$7.90'],
    [/€150\+/g, '$150+'],
    [/€19,90/g, '$19.90'],
    [/€7<small/g, '$7<small'],
    [/€119,00/g, '$119.00'],
    [/€59<small/g, '$59<small'],
    [/€4,91/g, '$4.91'],
    [/€60/g, '$60'],
    [/€247,00/g, '$247.00'],
    [/€<span id="price-value">/g, '$<span id="price-value">']
];

for (const [regex, replacement] of replacements) {
    content = content.replace(regex, replacement);
}

fs.writeFileSync('es.html', content, 'utf-8');
console.log('Translated successfully!');
